Họ và tên: Trương Quốc Bình

MSSV: 19521270

CÀI ĐẶT THUẬT TOÁN GRADIENT DESCENT BẰNG TENSORFLOW

In [1]:
import numpy as np
import tensorflow as tf

In [10]:
theta=tf.Variable(-4.0) #theta la bien so va se duoc cap nhat trong qua trinh huan luyen
#loss = lambda : theta**2 - 4*theta + 10 #(theta-2)^2+6
eps = 0.0001


In [11]:
@tf.function
def Loss(theta):
   return theta**2 - 4*theta + 10 #(theta-2)^2+6

In [12]:
opt = tf.keras.optimizers.SGD(learning_rate=0.1)

In [13]:
while True:
  with tf.GradientTape() as tape:
    loss = Loss(theta)
    print(loss)
  grads = tape.gradient(loss, [theta])
  print(grads)
  #cap nhat tham gia theta
  opt.apply_gradients(zip(grads, [theta]))
  #kiem tra xem khi nao dung
  if abs(grads[0].numpy()) <eps:
    break


tf.Tensor(42.0, shape=(), dtype=float32)
[<tf.Tensor: shape=(), dtype=float32, numpy=-12.0>]
tf.Tensor(29.04, shape=(), dtype=float32)
[<tf.Tensor: shape=(), dtype=float32, numpy=-9.6>]
tf.Tensor(20.7456, shape=(), dtype=float32)
[<tf.Tensor: shape=(), dtype=float32, numpy=-7.68>]
tf.Tensor(15.437183, shape=(), dtype=float32)
[<tf.Tensor: shape=(), dtype=float32, numpy=-6.144>]
tf.Tensor(12.039797, shape=(), dtype=float32)
[<tf.Tensor: shape=(), dtype=float32, numpy=-4.9151998>]
tf.Tensor(9.86547, shape=(), dtype=float32)
[<tf.Tensor: shape=(), dtype=float32, numpy=-3.93216>]
tf.Tensor(8.473901, shape=(), dtype=float32)
[<tf.Tensor: shape=(), dtype=float32, numpy=-3.1457279>]
tf.Tensor(7.583297, shape=(), dtype=float32)
[<tf.Tensor: shape=(), dtype=float32, numpy=-2.5165823>]
tf.Tensor(7.01331, shape=(), dtype=float32)
[<tf.Tensor: shape=(), dtype=float32, numpy=-2.0132658>]
tf.Tensor(6.648518, shape=(), dtype=float32)
[<tf.Tensor: shape=(), dtype=float32, numpy=-1.6106126>]
tf.Tensor(

In [16]:
print("theta toi uu: ", theta.numpy())
print("Gia tri nho nhat cua ham loss: ", loss.numpy())

theta toi uu:  1.999965
Gia tri nho nhat cua ham loss:  6.0
